# define cluster Role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
---
# define service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
---
# apply cluster role binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: alnair
        scrape_interval: 5s
        kubernetes_sd_configs:
          - role: pod
            selectors:
              - role: pod
                label: "app=alnair-exporter"
      - job_name: cadvisor
        scrape_interval: 5s
        #tls_config:
        #  ca_file: /var//run/secrets/kubernetes.io/serviceaccount/ca.crt
        #  insecure_skip_verify: true
        #bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        #scheme: https
        kubernetes_sd_configs:
          - role: pod
            selectors:
              - role: pod
                label: "name=cadvisor"
        relabel_configs:
        - source_labels: [__address__]
          regex: ^(.*):\d+$
          target_label: __address__
          replacement: $1:8080
        #- target_label: __scheme__
        #  replacement: http
        # Host name
        - source_labels: [__meta_kubernetes_pod_node_name]
          target_label: instance
        # Extract some labels mzm
        - source_labels: [__meta_kubernetes_host_ip]
          target_label: node_ip
      - job_name: 'profiler-pods'
        scrape_interval: 1s # cannot scrape with higher frequency if some worker takes longer time to response
        #scrape_timeout: 5s #scrape timeout cannot less than scrape interval 
        metrics_path: '/metrics' # default
        #tls_config:
        #  insecure_skip_verify: true
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - default
            selectors:
              - role: pod
                label: "app=profiler" 
        relabel_configs:
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
#        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
#          regex: true
#          action: keep
---
# prometheus server deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--storage.tsdb.retention.time=120h"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
            - "--web.enable-lifecycle"  # for runtime config update reload $curl -X POST http://localhost:9090/-/reload
          ports:
            - containerPort: 9090
              hostPort: 9090
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-config
  
        - name: prometheus-storage-volume
          emptyDir: {}
---
# deploy services
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30909
---
#pushgateway deployment

---
# pushgateway service


